### ISSUE TITLE
Bazel doesn't check for supported features like mallinfo while upstream LLVM does

### ISSUE THREAD

**Issue by PureTryOut** [google/llvm-bazel#132]
In an effort to get Tensorflow working on Alpine Linux with Musl libc (instead of glibc), I encountered an issue while it compiled LLVM:

```
ERROR: /home/bart/.cache/bazel/_bazel_bart/f5cee94bd62e1be0d824a974250af519/external/llvm-project/llvm/BUILD:3766:11: C++ compilation of rule '@llvm-project//llvm:Support' failed (Exit 1)
In file included from external/llvm-project/llvm/lib/Support/Process.cpp:101:
external/llvm-project/llvm/lib/Support/Unix/Process.inc: In static member function 'static size_t llvm::sys::Process::GetMallocUsage()':
external/llvm-project/llvm/lib/Support/Unix/Process.inc:93:19: error: aggregate 'llvm::sys::Process::GetMallocUsage()::mallinfo mi' has incomplete type and cannot be defined
   93 |   struct mallinfo mi;
      |                   ^~
external/llvm-project/llvm/lib/Support/Unix/Process.inc:94:10: error: '::mallinfo' has not been declared
   94 |   mi = ::mallinfo();
      |          ^~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

Basically `mallinfo` is not supported on Musl libc, and on upstream LLVM it uses guards to make sure it doesn't get compiled. A combination of [CMake](https://github.com/llvm/llvm-project/blob/main/llvm/cmake/config-ix.cmake#L234) checking if the symbol exists, and [a guard in the code](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Unix/Process.inc#L34).

It seems however that Bazel doesn't check that and always sets `HAVE_MALLINFO`, even if not true?

I made an issue on Tensorflow but [got redirected here](https://github.com/tensorflow/tensorflow/issues/45446#issuecomment-758115874).

**Comment by GMNGeoffrey** [comment]
Since it seems like your primary goal is building TF, I commented on your TF issue. TF does not currently use these build files (although we are trying to converge and just use these).

**Comment by GMNGeoffrey** [comment]
This repository is archived. Please direct issues to the upstream LLVM repository
