### ISSUE TITLE
undefined reference to 'log10'

### ISSUE THREAD

**Issue by mmcloughlin** [google/llvm-bazel#188]
Apologies if this is a dumb question. I can't quite tell if this is an error on my end or `llvm-bazel`. Any help appreciated.

When I build `@llvm-bazel//...` I'm seeing:

```
bazel-out/host/bin/external/llvm-project/llvm/_objs/Support/Signals.o:Signals.cpp:function printSymbolizedStackTrace(llvm::StringRef, void**, int, llvm::raw_ostream&): error: undefined reference to 'log10'
bazel-out/host/bin/external/llvm-project/llvm/_objs/Support/Signals.o:Signals.cpp:function printSymbolizedStackTrace(llvm::StringRef, void**, int, llvm::raw_ostream&): error: undefined reference to 'log10'
```

This is when linking `mlir/mlir-linalg-ods-yaml-gen` but it appears to happen as soon as it attempts to link anything. It seems there might be an `-lm` missing somewhere.

My configuration is essentially borrowed from `xls` https://github.com/google/xls/tree/main/dependency_support/llvm_bazel, but I played around with LLVM versions in case that made a difference.

```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def llvm_workspace():
    # newest
    LLVM_COMMIT = "2f69975683f5b6ea7df79f335f96b889a4bddecd"

    # xls
    # LLVM_COMMIT = "628dda08b82fcedcd9e89c9ef7850388e988bf68"  # 2021-04-07
    # LLVM_SHA256 = "b48c8c63c17631cc0160e1359c1e977188aa6cf5924cfd4b5664397effe65f30"
    # LLVM_BAZEL_SHA256 = "259684aa19af62201bd6a261faf315aff8a17dc8bcafcaed372b14108a872f71"

    # llvm-bazel example
    # LLVM_COMMIT = "499bce3abab8a362b9b4197944bd40b826c736c4"
    # LLVM_SHA256 = "a154965dfeb2b5963acc2193bc334ce90b314acbe48430ba310d8a7c7a20de8b"
    # LLVM_BAZEL_SHA256 = "a05a83300b6b4d8b45c9ba48296c06217f3ea27ed06b7e698896b5a3b2ed498d"

    http_archive(
        name = "llvm-bazel",
        # sha256 = LLVM_BAZEL_SHA256,
        strip_prefix = "llvm-bazel-llvm-project-{llvm_commit}/llvm-bazel".format(llvm_commit = LLVM_COMMIT),
        url = "https://github.com/google/llvm-bazel/archive/refs/tags/llvm-project-{llvm_commit}.tar.gz".format(llvm_commit = LLVM_COMMIT),
    )

    http_archive(
        name = "llvm-project-raw",
        build_file_content = "#empty",
        # sha256 = LLVM_SHA256,
        strip_prefix = "llvm-project-" + LLVM_COMMIT,
        url = "https://github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
    )
```

and

```bzl
load("@llvm-bazel//:terminfo.bzl", "llvm_terminfo_disable")
load("@llvm-bazel//:zlib.bzl", "llvm_zlib_disable")
load("@llvm-bazel//:configure.bzl", "llvm_configure")

def llvm_initialize():
    llvm_terminfo_disable(
        name = "llvm_terminfo",
    )

    llvm_zlib_disable(
        name = "llvm_zlib",
    )

    # This macro creates a new repo containing the LLVM source code downloaded
    # as llvm-project-raw and the BUILD files from llvm-bazel (contained in the
    # directory llvm-project-overlay). This new repo is constructed as symlinks
    # into these two directories.
    llvm_configure(
        # Name of resulting repo (e.g., "@llvm-project")
        name = "llvm-project",

        # The path to the directory containing the LLVM BUILD files within
        # llvm-bazel.
        overlay_path = "llvm-project-overlay",
        overlay_workspace = "@llvm-bazel//:WORKSPACE",

        # Project containing the llvm source code downloaded with http_archive.
        src_path = ".",
        src_workspace = "@llvm-project-raw//:WORKSPACE",
    )
```

Really appreciate this effort. Thanks for your help.

**Comment by GMNGeoffrey** [comment]
What's the command you're running and what platform are you on?

**Comment by GMNGeoffrey** [comment]
I'd guess you're not passing `--config=generic_clang` or similar to specify the config, which means you're not getting the right C++ version

**Comment by GMNGeoffrey** [comment]
(log10 is since C++11: https://en.cppreference.com/w/cpp/numeric/math/log10)

**Comment by mmcloughlin** [comment]
I'm running ` bazel build @llvm-project//...`, but it's in our bazel monorepo at my company (Aurora Innovation) so it's difficult to share the exact configuration. I'm essentially certain it's not to do with the C++ version.

If I inspect the command line that fails (`bazel-out/host/bin/external/llvm-project/mlir/mlir-linalg-ods-yaml-gen-2.params`) I don't see `-lm`.

```
$ tail bazel-out/host/bin/external/llvm-project/mlir/mlir-linalg-ods-yaml-gen-2.params
bazel-out/host/bin/external/llvm-project/llvm/_objs/Support/xxhash.o
--end-lib
--start-lib
bazel-out/host/bin/external/llvm-project/llvm/_objs/Demangle/Demangle.o
bazel-out/host/bin/external/llvm-project/llvm/_objs/Demangle/ItaniumDemangle.o
bazel-out/host/bin/external/llvm-project/llvm/_objs/Demangle/MicrosoftDemangle.o
bazel-out/host/bin/external/llvm-project/llvm/_objs/Demangle/MicrosoftDemangleNodes.o
--end-lib
-ldl
-lstdc++
```

I guess I should pull down your exact bazel config in the example and see if that fails.

**Comment by GMNGeoffrey** [comment]
Ah also since this is a linker error, you're probably right that it's not a version issue

I've pattern matched too hard on "can't find thing in std -> missing c++ version specification"

**Comment by GMNGeoffrey** [comment]
I think you're right that we're just missing `-lm` here. We've already got it on `mlir-linalg-ods-gen`. I honestly don't understand why this gets automatically detected on some platforms and not others. Are there any other binaries that need it?

**Comment by mmcloughlin** [comment]
Yes, but not on `mlir-linalg-ods-yaml-gen`:

https://github.com/google/llvm-bazel/blob/d4877ca635cc4afc36979b8409564518f07f978a/llvm-bazel/llvm-project-overlay/mlir/BUILD#L4414-L4427

I'm speculating here, but should `-lm` actually be on the library rather than the binary target? Like here:

https://github.com/google/llvm-bazel/blob/d4877ca635cc4afc36979b8409564518f07f978a/llvm-bazel/llvm-project-overlay/llvm/BUILD#L213-L219

**Comment by GMNGeoffrey** [comment]
Given that your error is coming from llvm Support, I'd guess the answer is ~"all of them" :stuck_out_tongue: I then wonder if we shouldn't just add this to Support itself. @chandlerc thoughts? Similarly, we've got `-lpthread` on a bunch of the binaries, but IIUC, having `-pthread` as we do in the llvm Support library should already mean that everything transitively has that and `-pthread` is a superset of `-lpthread`. It seems like we're sticking these options at leaves when they should be in the library that actually needs it

**Comment by mmcloughlin** [comment]
Ah, seems we maybe came to that conclusion at the same time :)

Yes I think `-lm` should be on the Support target and would be inherited (if I understand `linkopts` correctly). Because the `log10` call is in that library.

https://github.com/llvm/llvm-project/blob/2f69975683f5b6ea7df79f335f96b889a4bddecd/llvm/lib/Support/Signals.cpp#L196

**Comment by GMNGeoffrey** [comment]
Can you test if add `-lm` to `llvm:Support` fixes your issue? I'll send a PR dropping all the linkopts from the leaf binaries and adding `-lm` to `llvm:Support`, which I think is the right thing to do. There will be some weirdness by nature of this being a transitive thing (line `includes`) that means we might have some things happen to work because they dep on Support even though there are other libraries that really need these options and don't have them, but I'm not sure how to avoid that

**Comment by GMNGeoffrey** [comment]
(I can't test because for reasons that remain unclear to me this doesn't fail on my machine. Something is magically figuring out it needs math and pulling it in)

**Comment by chandlerc** [comment]
FWIW, adding `-lm` sounds fine to me.

Arguably, Bazel's C++ toolchain might should do this for us since it is part of C/C++. But there's no reason to stress about why that isn't happening, adding it to our target seems reasonable.

**Comment by GMNGeoffrey** [comment]
Great, sent you a PR :-)

We could also add this to linkopts (but that would require @mmcloughlin also adding it to the linkopts of their toolchain)

**Comment by mmcloughlin** [comment]
For what it's worth, just adding `--host_linkopt=-lm` to my command line appears to fix everything for me.

I suspect #189 should be enough. I'll let you know if not.

As for why this was magically working for you, I'm wondering if `-lm` is an automatic default dependency in your toolchain/stdlib. Something like hinted in this answer: https://stackoverflow.com/a/1033940.

**Comment by GMNGeoffrey** [comment]
Yeah that makes sense. It's not clear to me whether the "right" way to do this is to add it to libraries or just say it has to be part of the toolchain. This seems fine for now though :slightly_smiling_face: thanks for helping root out this issue.

**Comment by mmcloughlin** [comment]
Well, my instinct is saying this was working "by accident" for you before. I think moving the `-lm` is correct. It would just be reassuring to repro this in the CI system to ensure similar issues are caught in future.

Anyway, thanks for acting so fast! We had our own in-house bazel rules before and it was nasty. This repo is a far better solution.

**Comment by GMNGeoffrey** [comment]
Yes I agree this was working by accident before. I guess my question was whether it's better to add `-lm` to a specific library that needs it or just declare this part of the standard library to be required (in the same way we say c++14 is required) at the level of the toolchain. The fact that some toolchains seem to already be doing this for us muddied things a bit :grin:


> Anyway, thanks for acting so fast! We had our own in-house bazel rules before and it was nasty. This repo is a far better solution.

We have like 10 different copies of in-house bazel rules, so it's even better :stuck_out_tongue: FYI the contents of this repo will shortly (ish) be moving into the llvm monorepo proper (https://github.com/llvm/llvm-www/blob/main/proposals/LP0002-BazelBuildConfiguration.md). The delay from my end has been making sure I have folks at Google aligned so we can quickly delete our various internal copies when that happens.

So heads up that the precise way to integrate with this will change a little bit (though should just get easier)

**Comment by mmcloughlin** [comment]
Awesome. In-tree will be even better 😃
