### ISSUE TITLE
http-archive-demo broken

### ISSUE THREAD

**Issue by nickdesaulniers** [google/llvm-bazel#219]
```sh
$ cd /tmp
$ git clone https://github.com/google/llvm-bazel.git
$ git checkout -b demo origin/http-archive-demo
$ cd http-archive-demo
$ bazel-3.3.1 build @llvm-project//clang
...
<huge warning spew>
```

**Comment by GMNGeoffrey** [comment]
Sorry I was OOO

You will need to specify one of the configs to indicate the compiler as described in https://github.com/google/llvm-bazel#usage, e.g.

```shell
bazel-3.3.1 build --config=generic_clang @llvm-project//clang
```

Also the "warning spew" is likely the thing that will help diagnose issues, so please include it in your reports (you can throw it in a gist if it's too big)

**Comment by GMNGeoffrey** [comment]
I built this successfully

```shell
cd /tmp
git clone https://github.com/google/llvm-bazel.git
cd llvm-bazel/
git checkout origin/http-archive-demo
cd http-archive-demo
bazel-3.3.1 build --config=generic_clang @llvm-project//clang
```

Please open an issue with the errors you see, if you run into another issue.
