### ISSUE TITLE
ability to statically link clang?

### ISSUE THREAD

**Issue by nickdesaulniers** [google/llvm-bazel#220]
I'm not super familiar with blaze build rules, but it looks like for `cc_binary` `linkstatic` is default `True` [link](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary.linkstatic), but builds of clang via:
```sh
$ bazel-3.3.1 build --config=generic_clang @llvm-project//clang
$ llvm-readelf -d ./bazel-bin/external/llvm-project/clang/clang | grep NEEDED
  0x0000000000000001 (NEEDED)       Shared library: [libstdc++.so.6]
  0x0000000000000001 (NEEDED)       Shared library: [libm.so.6]
  0x0000000000000001 (NEEDED)       Shared library: [libdl.so.2]
  0x0000000000000001 (NEEDED)       Shared library: [libgcc_s.so.1]
  0x0000000000000001 (NEEDED)       Shared library: [libpthread.so.0]
  0x0000000000000001 (NEEDED)       Shared library: [libc.so.6]
  0x0000000000000001 (NEEDED)       Shared library: [ld-linux-x86-64.so.2]
```
is there something changing the implicit default? Is there a way to force linkstatic?
```diff
diff --git a/llvm-bazel/llvm-project-overlay/clang/BUILD.bazel b/llvm-bazel/llvm-project-overlay/clang/BUILD.bazel
index 263cf421a1d4..cc9c41d38f65 100644
--- a/llvm-bazel/llvm-project-overlay/clang/BUILD.bazel
+++ b/llvm-bazel/llvm-project-overlay/clang/BUILD.bazel
@@ -1909,6 +1909,7 @@ cc_binary(
     deps = [
         ":clang-driver",
     ],
+    linkstatic = 1,
 )
 
 cc_binary(
```
doesn't seem to do anything.

**Comment by jesec** [comment]
You need `--features=fully_static_link`.

Note that I haven't tried it with this project, though. I came across this project from the issue in ClangBuiltLinux. Good to know that there are Bazel rules for LLVM, and great work!

ref: https://docs.bazel.build/versions/master/be/c-cpp.html

**Comment by chandlerc** [comment]
Note: 'linkstatic` in Bazel is *not* a fully static link. It links the *bazel dependencies* statically. It still produces a dynamic executable and system libraries are still linked dynamically.

You can try to use `fully_static_link`, but this is not a well tested path and I'm not aware of anyone trying to reliably make it work (I'm not at least).

**Comment by chandlerc** [comment]
I don't think there is a bug here at all, so closing. But reopen if needed.
