### ISSUE TITLE
hermiticity issue?

### ISSUE THREAD

**Issue by nickdesaulniers** [google/llvm-bazel#221]
```sh
$ readelf -p .comment bazel-bin/external/llvm-project/clang/clang

String dump of section '.comment':
  [     1]  GCC: (Debian 10.2.1-6+build2) 10.2.1 20210110
  [    2f]  Nick Desaulniers clang version 13.0.0 (git@github.com:llvm/llvm-project.git 7cd07d339022ef92148e27e8fe12f65865f707d9)
```
so it seems the `.comment` section found my local build of clang for parts of the build; it seems this binary is composed of object files built with GCC AND clang.  That's unexpected.

**Comment by chandlerc** [comment]
Not if you're statically linking system archives into the executable?

**Comment by GMNGeoffrey** [comment]
Seems like this is WAI. Nick, please reopen if you disagree.
