### ISSUE TITLE
Add an LLD cc_binary target to OSS llvm-bazel

### ISSUE THREAD

**Issue by benvanik** [google/llvm-bazel#228]
We need to build lld as part of our toolchain (alongside other binaries like llvm-ar and mlir-tblgen). This is currently missing in the llvm-bazel open source release but seems to exist inside of google (though it may require some untangling).

**Comment by GMNGeoffrey** [comment]
This won't be added here, but is available in the upstream build files with https://reviews.llvm.org/D107414
