### ISSUE TITLE
Convert `gentbl` from a macro to a rule

### ISSUE THREAD

**Issue by ScottTodd** [google/llvm-bazel#92]
Context: https://github.com/google/llvm-bazel/pull/85

In order to `select()` flags based on the host environment, a rule should be used.

**Comment by GMNGeoffrey** [comment]
The MLIR version of gentbl is now a rule. We need to migrate LLVM over to the same rule as well. The only differences between them were the various include hacks, which the rule gets rid of.

**Comment by GMNGeoffrey** [comment]
This repository is archived. Please direct issues to the upstream LLVM repository
